// Code generated by the Encore v1.53.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}.kapil.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the api-hszi Encore application.
 */
export default class Client {
    public readonly gateway: gateway.ServiceClient
    public readonly migration: migration.ServiceClient
    public readonly s3: s3.ServiceClient
    public readonly terabox: terabox.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.gateway = new gateway.ServiceClient(base)
        this.migration = new migration.ServiceClient(base)
        this.s3 = new s3.ServiceClient(base)
        this.terabox = new terabox.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace gateway {
    export interface AuthParams {
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.newAuthSession = this.newAuthSession.bind(this)
            this.refreshSession = this.refreshSession.bind(this)
        }

        /**
         * Create a new session in Redis and send via cookie
         */
        public async newAuthSession(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/session/new`, body, options)
        }

        /**
         * Refresh an active session
         * Returns a new session ID and invalidates the old one
         */
        public async refreshSession(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/session/refresh`, body, options)
        }
    }
}

export namespace migration {
    export interface BackfillThumbnailRequest {
        limit?: number
        /**
         * Timestamp (seconds) at which to capture thumbnail.
         * 0 = use Terabox's own thumbUrl (default).
         * >0 = use ffmpeg to extract frame at this timestamp.
         */
        seconds?: number
    }

    export interface CheckStatusRequest {
        "bucket_name"?: string
        "bucket_id"?: number
    }

    export interface CheckTeraboxFileRequest {
        path: string
        "bucket_id"?: number
    }

    export interface FileStatus {
        id: number
        filename: string
        key: string
        "bucket_id": number | null
        "tb_bucket_id": number | null
        "bucket_name"?: string
        migrated: boolean
    }

    export interface MigrateS3Request {
        "dry_run"?: boolean
        "bucket_id"?: number
        all?: boolean
    }

    export interface MigrationResult {
        success: boolean
        stats: {
            totalBuckets: number
            totalFiles: number
            migratedFiles: number
            failedFiles: number
            durationMinutes: number
        }
        errors: {
            bucket: string
            file: string
            error: string
        }[]
        message?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.backfillThumbnails = this.backfillThumbnails.bind(this)
            this.checkMigrationStatus = this.checkMigrationStatus.bind(this)
            this.checkTeraboxFile = this.checkTeraboxFile.bind(this)
            this.migrateS3ToTerabox = this.migrateS3ToTerabox.bind(this)
        }

        public async backfillThumbnails(params: BackfillThumbnailRequest): Promise<{
            processed: number
            updated: number
            errors: number
            lastError?: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/migration/backfill-thumbnails`, JSON.stringify(params))
            return await resp.json() as {
                processed: number
                updated: number
                errors: number
                lastError?: string
            }
        }

        public async checkMigrationStatus(params: CheckStatusRequest): Promise<{
            "bucket_info"?: any
            "files_in_db": FileStatus[]
            "s3_bucket_id"?: number
            "total_files": number
            "migrated_files": number
            "pending_files": number
        }> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "bucket_id": params["bucket_id"] === undefined ? undefined : String(params["bucket_id"]),
                "bucket_name": params["bucket_name"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/migration/check-status`, undefined, { query })
            return await resp.json() as {
                "bucket_info"?: any
                "files_in_db": FileStatus[]
                "s3_bucket_id"?: number
                "total_files": number
                "migrated_files": number
                "pending_files": number
            }
        }

        public async checkTeraboxFile(params: CheckTeraboxFileRequest): Promise<{
            exists: boolean
            path: string
            "file_info"?: any
            error?: string
        }> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "bucket_id": params["bucket_id"] === undefined ? undefined : String(params["bucket_id"]),
                path: params.path,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/migration/check-terabox-file`, undefined, { query })
            return await resp.json() as {
                exists: boolean
                path: string
                "file_info"?: any
                error?: string
            }
        }

        /**
         * Migrate S3 buckets to Terabox
         */
        public async migrateS3ToTerabox(params: MigrateS3Request): Promise<MigrationResult> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/migration/s3-to-terabox`, JSON.stringify(params))
            return await resp.json() as MigrationResult
        }
    }
}

export namespace s3 {
    export interface JobStatusResponse {
        "job_id": string
        status: "pending" | "processing" | "completed" | "failed"
        "total_urls": number
        completed: number
        failed: number
        "created_at": string
        "updated_at": string
    }

    export interface RemoteUploadRequest {
        /**
         * URLs to download and upload to S3
         */
        urls: string[]

        /**
         * Target bucket ID (required)
         */
        "bucket_id": number

        /**
         * Optional folder/prefix for uploaded files
         */
        prefix?: string
    }

    export interface RemoteUploadResponse {
        /**
         * Job ID for tracking
         */
        "job_id": string

        /**
         * Number of URLs queued
         */
        "queued_count": number

        /**
         * Status message
         */
        message: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getJobStatus = this.getJobStatus.bind(this)
            this.localUpload = this.localUpload.bind(this)
            this.remoteUpload = this.remoteUpload.bind(this)
        }

        /**
         * Get job status by ID
         */
        public async getJobStatus(job_id: string): Promise<JobStatusResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/job/status/${encodeURIComponent(job_id)}`)
            return await resp.json() as JobStatusResponse
        }

        /**
         * Local file upload endpoint
         * Accepts multipart/form-data with file and bucket_id
         */
        public async localUpload(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/s3/local`, body, options)
        }

        /**
         * Submit URLs for remote upload (fire and forget)
         * Returns immediately after queuing the URLs for processing
         */
        public async remoteUpload(params: RemoteUploadRequest): Promise<RemoteUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/s3/remote`, JSON.stringify(params))
            return await resp.json() as RemoteUploadResponse
        }
    }
}

export namespace terabox {
    export interface BatchUploadRequest {
        /**
         * URL pattern with `{n}` as the placeholder for the number.
         * Example: "https://cdn.domain.com/{n}.mp4"
         */
        pattern: string

        /**
         * Start number (inclusive), default 1
         */
        start?: number

        /**
         * End number (inclusive)
         */
        end: number

        /**
         * Optional zero-padding width, e.g. 3 → 001, 002 ...
         */
        pad?: number

        /**
         * The folder ID to determine which Terabox bucket to use
         */
        "folder_id": number

        /**
         * Optional: encrypt uploaded files
         */
        encrypt?: boolean

        /**
         * Optional cookie for fetching
         */
        cookie?: string

        /**
         * Optional User-Agent for fetching
         */
        "user_agent"?: string
    }

    export interface BatchUploadResponse {
        success: boolean
        /**
         * Total URLs generated from the pattern
         */
        total: number

        /**
         * Number queued for upload
         */
        queued: number

        /**
         * Number skipped (duplicates)
         */
        skipped: number

        items?: {
            url: string
            "job_id"?: string
            status: "queued" | "duplicate" | "error"
            error?: string
        }[]
        error?: string
    }

    export interface CreateBucketRequest {
        email: string
        password: string
    }

    export interface DebugFileResponse {
        file: any
        meta: any
        list: any
        manualMeta: any
        manualSearch: any
        categoryList: any
        shortUrlList: any
        keys?: any
    }

    export interface DeleteRequest {
        paths: string[]
        "bucket_id"?: number
        userAgent?: string
    }

    export interface DownloadRequest {
        url?: string
        password?: string
        "bucket_id"?: number
        "share_id"?: string
        userAgent?: string
    }

    export interface FileManagerRequest {
        operation: "move" | "copy" | "rename" | "delete"
        filelist: {
            path: string
            dest?: string
            newname?: string
        }[]
        "bucket_id": number
        userAgent?: string
    }

    export interface GetUploadHostRequest {
        "bucket_id"?: number
        userAgent?: string
    }

    export interface PrecreateFileRequest {
        "remote_dir": string
        file: string
        size: number
        hash: {
            crc32: number
            slice: string
            file: string
            etag?: string
            chunks?: string[]
        }
        "bucket_id"?: number
        userAgent?: string
    }

    export interface RemoteUploadRequest {
        url: string
        "remote_dir"?: string
        filename?: string
        "bucket_id"?: number
        userAgent?: string
        fileId?: number
        headers?: { [key: string]: string }
        encrypt?: boolean
        "source_url"?: string
    }

    export interface ScrapeRequest {
        /**
         * The website URL to scrape for video links
         */
        url: string

        /**
         * The folder ID to determine which Terabox bucket to use
         */
        "folder_id": number

        /**
         * Optional cookie string to bypass Cloudflare or authentication
         */
        cookie?: string

        /**
         * Optional User-Agent to use when fetching the page
         */
        "user_agent"?: string

        /**
         * Optional: encrypt uploaded files
         */
        encrypt?: boolean
    }

    export interface ScrapeResponse {
        success: boolean
        /**
         * Number of videos found on the page
         */
        found: number

        /**
         * Number of new videos queued for upload (not duplicates)
         */
        queued: number

        /**
         * Number of videos skipped because they already exist
         */
        skipped: number

        /**
         * Details of queued items
         */
        items?: {
            "video_url": string
            "job_id"?: string
            status: "queued" | "duplicate"
        }[]

        error?: string
    }

    export interface StreamMessage {
        type: string
        data: any
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createBucket = this.createBucket.bind(this)
            this.debugFileInfo = this.debugFileInfo.bind(this)
            this.refreshExpiringCookiesHandler = this.refreshExpiringCookiesHandler.bind(this)
            this.serveStreamM3U8 = this.serveStreamM3U8.bind(this)
            this.streamJobUpdates = this.streamJobUpdates.bind(this)
            this.teraboxBackfillDuration = this.teraboxBackfillDuration.bind(this)
            this.teraboxBackfillQuality = this.teraboxBackfillQuality.bind(this)
            this.teraboxBackfillShareId = this.teraboxBackfillShareId.bind(this)
            this.teraboxBatchUpload = this.teraboxBatchUpload.bind(this)
            this.teraboxDecryptFile = this.teraboxDecryptFile.bind(this)
            this.teraboxDelete = this.teraboxDelete.bind(this)
            this.teraboxDownload = this.teraboxDownload.bind(this)
            this.teraboxDownloadProxy = this.teraboxDownloadProxy.bind(this)
            this.teraboxEmptyRecyleBin = this.teraboxEmptyRecyleBin.bind(this)
            this.teraboxEncryptFile = this.teraboxEncryptFile.bind(this)
            this.teraboxFileManager = this.teraboxFileManager.bind(this)
            this.teraboxGenerateGifPreview = this.teraboxGenerateGifPreview.bind(this)
            this.teraboxGetRecyleBin = this.teraboxGetRecyleBin.bind(this)
            this.teraboxGetUploadHost = this.teraboxGetUploadHost.bind(this)
            this.teraboxLocalUpload = this.teraboxLocalUpload.bind(this)
            this.teraboxPrecreateFile = this.teraboxPrecreateFile.bind(this)
            this.teraboxProxy = this.teraboxProxy.bind(this)
            this.teraboxQuota = this.teraboxQuota.bind(this)
            this.teraboxRemoteUpload = this.teraboxRemoteUpload.bind(this)
            this.teraboxS3FileResolver = this.teraboxS3FileResolver.bind(this)
            this.teraboxS3Proxy = this.teraboxS3Proxy.bind(this)
            this.teraboxS3Resolver = this.teraboxS3Resolver.bind(this)
            this.teraboxSaveVideo = this.teraboxSaveVideo.bind(this)
            this.teraboxScrape = this.teraboxScrape.bind(this)
            this.teraboxStream = this.teraboxStream.bind(this)
            this.teraboxThumbnail = this.teraboxThumbnail.bind(this)
            this.teraboxUpdateThumb = this.teraboxUpdateThumb.bind(this)
            this.updateDuration = this.updateDuration.bind(this)
            this.updateQuality = this.updateQuality.bind(this)
            this.updateShareId = this.updateShareId.bind(this)
        }

        /**
         * Create new Terabox bucket (auto-fetches all other info)
         */
        public async createBucket(params: CreateBucketRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/buckets`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        public async debugFileInfo(params: {
            fileId: number
        }): Promise<DebugFileResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/debug/file-info`, JSON.stringify(params))
            return await resp.json() as DebugFileResponse
        }

        /**
         * Proactive cookie expiration monitor
         * Runs daily at 2 AM to check for expiring cookies and refresh them
         */
        public async refreshExpiringCookiesHandler(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/terabox/cron/refresh-expiring-cookies`)
        }

        /**
         * Serve a playable M3U8 stream for a file
         */
        public async serveStreamM3U8(method: "GET", fileId: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/terabox/stream/${encodeURIComponent(fileId)}`, body, options)
        }

        public async streamJobUpdates(jobId: string): Promise<StreamIn<StreamMessage>> {
            return await this.baseClient.createStreamIn(`/terabox/jobs/${encodeURIComponent(jobId)}/stream`)
        }

        public async teraboxBackfillDuration(params: {
            limit?: number
        }): Promise<migrations.BackfillResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/backfill-duration`, JSON.stringify(params))
            return await resp.json() as migrations.BackfillResponse
        }

        public async teraboxBackfillQuality(params: {
            limit?: number
        }): Promise<migrations.BackfillResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/backfill-quality`, JSON.stringify(params))
            return await resp.json() as migrations.BackfillResponse
        }

        public async teraboxBackfillShareId(params: {
            limit?: number
        }): Promise<migrations.BackfillResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/backfill-shareid`, JSON.stringify(params))
            return await resp.json() as migrations.BackfillResponse
        }

        /**
         * POST /terabox/batch-upload
         * 
         * Generate URLs from a pattern and queue each for remote upload.
         * Pattern uses `{n}` as the numeric placeholder.
         * 
         * Example: pattern="https://cdn.example.com/{n}.mp4", start=1, end=10
         * → queues https://cdn.example.com/1.mp4 … https://cdn.example.com/10.mp4
         * 
         * Use `pad` for zero-padded numbers: pad=3 → 001, 002 … 010
         */
        public async teraboxBatchUpload(params: BatchUploadRequest): Promise<BatchUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/batch-upload`, JSON.stringify(params))
            return await resp.json() as BatchUploadResponse
        }

        /**
         * Decrypt a file in place (Replaces encrypted file with plaintext)
         */
        public async teraboxDecryptFile(params: {
            "file_id": number
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/decrypt-file`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Delete files/folders
         */
        public async teraboxDelete(params: DeleteRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                paths: params.paths,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/delete`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Get download links from a shared Terabox URL
         */
        public async teraboxDownload(params: DownloadRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                password: params.password,
                "share_id": params["share_id"],
                url: params.url,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/download`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Get download stream for a file (Proxied for Encrypted files)
         */
        public async teraboxDownloadProxy(method: "GET", fileId: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/terabox/download/${encodeURIComponent(fileId)}`, body, options)
        }

        public async teraboxEmptyRecyleBin(params: {
            "bucket_id"?: number
            userAgent?: string
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/recycle-bin/empty`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Encrypt an existing Terabox file (In-Place / Replace)
         * Downloads the file, encrypts it using v2 algorithm, uploads back, and updates DB
         */
        public async teraboxEncryptFile(params: {
            "file_id": number
            force?: boolean
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/encrypt-file`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Terabox File manager copy/move/rename/delete files
         * operation - copy (file copy), move (file movement), rename (file renaming), and delete (file deletion)
         * opera=copy: filelist: [{"path":"/hello/test.mp4","dest":"","newname":"test.mp4"}]
         * opera=move: filelist: [{"path":"/test.mp4","dest":"/test_dir","newname":"test.mp4"}]
         * opera=rename: filelist：[{"path":"/hello/test.mp4","newname":"test_one.mp4"}]
         * opera=delete: filelist: ["/test.mp4"]
         */
        public async teraboxFileManager(params: FileManagerRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                filelist: params.filelist,
                operation: params.operation,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/file-manager`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Generate a GIF preview for a file
         */
        public async teraboxGenerateGifPreview(params: {
            "file_id": number
        }): Promise<{
            success: boolean
            url: string | null
            message: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/generate-gif-preview`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                url: string | null
                message: string
            }
        }

        /**
         * Get recycle bin contents
         */
        public async teraboxGetRecyleBin(params: {
            "bucket_id"?: number
            userAgent?: string
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/recycle-bin`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Get Upload Host
         */
        public async teraboxGetUploadHost(params: GetUploadHostRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/get-upload-host`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Upload local file via multipart/form-data
         * Uses api.raw to handle large files (up to 1GB)
         */
        public async teraboxLocalUpload(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/terabox/local-upload`, body, options)
        }

        /**
         * Precreate File
         */
        public async teraboxPrecreateFile(params: PrecreateFileRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                file: params.file,
                hash: params.hash,
                "remote_dir": params["remote_dir"],
                size: params.size,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/precreate-file`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * Proxy VIDEO segments to bypass hotlink protection (Generic Proxy)
         */
        public async teraboxProxy(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/terabox/proxy`, body, options)
        }

        /**
         * Get storage quota information
         */
        public async teraboxQuota(params: {
            "bucket_id"?: number
            userAgent?: string
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/quota`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        public async teraboxRemoteUpload(params: RemoteUploadRequest): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                encrypt: params.encrypt,
                fileId: params.fileId,
                filename: params.filename,
                headers: params.headers,
                "remote_dir": params["remote_dir"],
                "source_url": params["source_url"],
                url: params.url,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/remote-upload`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * S3 File ID Resolver for Cloudflare Worker (DB-backed files)
         * Returns download URL and headers by looking up file_id in database
         * Path: /s3/resolve/file/:id
         */
        public async teraboxS3FileResolver(method: "GET", id: string, filename: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/s3/resolve/file/${encodeURIComponent(id)}/${encodeURIComponent(filename)}`, body, options)
        }

        /**
         * S3-compatible object proxy for Cloudflare Caching
         * Path: /s3/object/:bucket/*key
         */
        public async teraboxS3Proxy(method: "GET", bucket: string, key: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/s3/object/${encodeURIComponent(bucket)}/${key.map(encodeURIComponent).join("/")}`, body, options)
        }

        /**
         * S3 Link Resolver for Cloudflare Worker
         * Returns download URL and headers (does NOT stream data)
         * Path: /s3/resolve/:bucket/*key
         */
        public async teraboxS3Resolver(method: "GET", bucket: string, key: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/s3/resolve/${encodeURIComponent(bucket)}/${key.map(encodeURIComponent).join("/")}`, body, options)
        }

        /**
         * Save Terabox file video (Async via Pub/Sub)
         */
        public async teraboxSaveVideo(params: {
            urls: string[]
            "bucket_id": number
            userAgent?: string
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                urls: params.urls,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/save-video`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        /**
         * POST /terabox/scrape
         * 
         * Scrape a website for video links and queue them for remote upload to Terabox.
         * Uses the source URL as the unique identifier for duplicate prevention.
         */
        public async teraboxScrape(params: ScrapeRequest): Promise<ScrapeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/scrape`, JSON.stringify(params))
            return await resp.json() as ScrapeResponse
        }

        /**
         * Get streaming link for a video file
         */
        public async teraboxStream(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/terabox/stream`, body, options)
        }

        /**
         * Get best thumbnail for a file shared
         */
        public async teraboxThumbnail(params: {
            "share_id": string
            "bucket_id": number
            userAgent?: string
        }): Promise<{
            success: boolean
            data?: any
            error?: string
            cause?: any
            errno?: number
        }> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "bucket_id": params["bucket_id"],
                "share_id": params["share_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/thumbnail`, JSON.stringify(body), { headers })
            return await resp.json() as {
                success: boolean
                data?: any
                error?: string
                cause?: any
                errno?: number
            }
        }

        public async teraboxUpdateThumb(params: migrations.UpdateThumbnailRequest): Promise<{
            success: boolean
            url: string | null
            message: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/update-thumbnail`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                url: string | null
                message: string
            }
        }

        /**
         * Generate and Update Duration for a single file
         */
        public async updateDuration(params: {
            "file_id": number
        }): Promise<{
            success: boolean
            message: string
            duration?: number
            error?: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/migration/update-duration`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                message: string
                duration?: number
                error?: string
            }
        }

        /**
         * Update quality for a single file (Generate then update)
         */
        public async updateQuality(params: {
            "file_id": number
        }): Promise<{
            success: boolean
            message: string
            quality?: string
            error?: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/migration/update-quality`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                message: string
                quality?: string
                error?: string
            }
        }

        /**
         * Generate and Update Share ID for a single file
         */
        public async updateShareId(params: {
            "file_id": number
        }): Promise<{
            success: boolean
            message: string
            "share_id"?: string
            error?: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/terabox/migration/update-share-id`, JSON.stringify(params))
            return await resp.json() as {
                success: boolean
                message: string
                "share_id"?: string
                error?: string
            }
        }
    }
}

export namespace migrations {
    export interface BackfillResponse {
        success: boolean
        processed: number
        updated: number
        remaining: number
        errors: number
        files?: any[]
    }

    export interface UpdateThumbnailRequest {
        "file_id": number
        seconds?: number
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ? parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
        .replaceAll("=", "")
        .replaceAll("+", "-")
        .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "api-hszi-Generated-TS-Client (Encore/v1.53.4)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                headers = { ...headers, ...authData.headers };
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                headers = { ...headers, ...authData.headers };
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                headers = { ...headers, ...authData.headers };
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = { ...this.headers, ...init.headers, ...headers }

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                init.headers = { ...init.headers, ...authData.headers };
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL + path + queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof (err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof (err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value: 'APIError',
            enumerable: false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
